modmap:
  - name: all
    remap:
      CapsLock: Control_L
      Control_L: CapsLock
keymap:
  - name: non_term
    application:
      not: [Alacritty]
    remap:
      C-d: delete
      C-f: right
      C-b: left
      C-p: up
      C-n: down
      C-e: end
      M-backspace: C-backspace
      M-f: C-right
      M-b: C-left
      C-slash: C-f 
  - name: term
    application:
      only: [Alacritty]
    remap:
      C-backspace: C-w
