[keyboard]
bindings = [
    # { key= "Back", mods= "Alt", chars= "\u0017" }
  { key="Key0",   mods="Control", action="ResetFontSize" }
]

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"


# [cursor.style]
# shape = "Beam"

# blinking = "Always"
#
# [cursor]
# blink_interval = 800


[colors.cursor]
text = "#282a36"
cursor = "#A0A0A0"

[window]
opacity = 0.99
padding.x = 10
padding.y = 10
startup_mode = "Maximized"
decorations = "None"

[font]
offset.x = 0                              # For letter spacing (default: 0)
offset.y = 0                              # For line spacing (default: 0)
# normal.family = "JetBrainsMono Nerd Font"
normal.family = "JetBrainsMonoNL NFP Light"
# normal.family = "SauceCodePro Nerd Font"
# normal.family = "InputMono Nerd Font Mono"
size = 13

# Dracula theme for Alacritty
# https://draculatheme.com/alacritty
#
# Color palette
# https://spec.draculatheme.com
#
# Instructions
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[colors.primary]

# background = "#282a36"
background = "#212229"
foreground = "#f8f8f2"
bright_foreground = "#ffffff"


[colors.vi_mode_cursor]

text = "CellBackground"
cursor = "CellForeground"

[colors.selection]

text = "CellForeground"
background = "#44475a"

[colors.normal]

black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]

black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.search.matches]

foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]

foreground = "#44475a"
background = "#ffb86c"

[colors.footer_bar]

background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.start]

foreground = "#282a36"
background = "#f1fa8c"

[colors.hints.end]

foreground = "#f1fa8c"
background = "#282a36"
